server:
  port: 8002

spring:
  application:
    name: cloud-payment-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
#      集群版
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
#注册在Eureka上的主机实例名字
  instance:
    instance-id: payment8002
    prefer-ip-address: true